version: "3.9"

services:
  app:
    container_name: iam_app
    build:
      context: .
      dockerfile: Docker/dockerfile/DockerfileApp
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - iam_network

networks:
  iam_network:
    name: iam_network
    driver: bridge

volumes:
  node_modules:
